# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page

# 4. Jekyll settings
sass:
 style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: US # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Blog Projects # Needed for Siteleaf
    output: true
    description: "Journey through Metis's Projects" # The post list page content
    feature_text: |
      Welcome to the Jennifer Phan's Blog
    feature_image: "https://i2.wp.com/digital-photography-school.com/wp-content/uploads/2012/09/Peter-West-Carey-Seattle2012-0908-6437-15.jpg?ssl=1"

# 6. Jekyll collections settings
defaults:
  -
    values:
      image: "https://avatars0.githubusercontent.com/u/34076265?s=400&u=dbb68a0b3db637b715aacb99ae6fcd250dc2a10e&v=4" # Default image for sharing

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
lang: en-GB # Set the site language
title: "Jennifer Phan's Blog" # Site name or title, also used in jekyll-seo-tag
logo: "http://static1.squarespace.com/static/58affa68414fb5edf9808f7a/t/58b509ff579fb328f5d781e4/1488259584451/high-qualty-JLP-logo-favicon.png?format=1000w" # Site logo, also used in jekyll-seo-tag
description: "My Metis's Projects" # Site description and default description, also used in jekyll-seo-tag
url: "https://jphan88.github.io" # Site url, also used in jekyll-seo-tag
baseurl: ""
repo: "https://github.com/jphan88/alembic"
email: "jphan88@gmail.com"
# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account
avatarurl: "https://avatars0.githubusercontent.com/u/34076265?s=400&u=dbb68a0b3db637b715aacb99ae6fcd250dc2a10e&v=4" # Uses avatars for favicons to get multple sites, eg Gravatar, Twitter, GitHub

# 8. Site navigation
navigation_header:
  Home: /
  Elements: /elements/
  Projects: /blog/
  Categories: /categories/
  Search: /search/



social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired

  #LinkedIn: https://www.linkedin.com/in/daviddarnes
  #Google+: https://plus.google.com/+jp
  GitHub: https://github.com/jphan88


sharing_links: # Appear at the bottom of single blog posts, uncomment and comment out as desired. Colours set the button colour
 # Twitter: "#1DA1F2"
  #facebook: "#3B5998"
  #Google+: "#DC4E41"
  # Pinterest: "#BD081C"
  # LinkedIn: "#0077B5"
  # tumblr: "#36465D"
  # Reddit: "#FF4500"
  # Hacker News: "#ff6600"
  # Designer News: "#2D72D9"
  # Email: ""
